/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ZihU3ePED9D
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Progress } from "@/components/ui/progress"
import { Card, CardHeader, CardContent, CardTitle } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import { ChartTooltipContent, ChartTooltip, ChartContainer } from "@/components/ui/chart"
import { PolarAngleAxis, PolarGrid, Radar, RadarChart, CartesianGrid, XAxis, Bar, BarChart, Line, LineChart } from "recharts"
import BarchartChart from "./barchartchart"
import RadarchartChart from "./radarchartChart"



export default async function Activities() {
  return (
    (<div className="min-h-screen bg-background">
      <header className="flex items-center justify-between p-4 bg-card shadow-md">
        <div className="flex items-center space-x-4">
          <div className="flex items-center space-x-2">
            <LogInIcon className="h-8 w-8" />
            <span className="text-2xl font-bold text-card-foreground">gyde.ai</span>
          </div>
          <nav className="hidden space-x-4 md:flex">
            <Link
              href="#"
              className="text-lg font-medium text-card-foreground"
              prefetch={false}>
              Home
            </Link>
            <Link
              href="#"
              className="text-lg font-medium text-card-foreground"
              prefetch={false}>
              Essays
            </Link>
            <Link
              href="#"
              className="text-lg font-medium text-card-foreground"
              prefetch={false}>
              Colleges
            </Link>
            <Link
              href="#"
              className="text-lg font-medium text-card-foreground"
              prefetch={false}>
              Activities
            </Link>
            <Link
              href="#"
              className="text-lg font-medium text-card-foreground"
              prefetch={false}>
              Planner
            </Link>
          </nav>
        </div>
        <div className="flex items-center space-x-4">
          <Button variant="ghost" className="rounded-full text-card-foreground">
            <BellIcon className="h-6 w-6" />
          </Button>
          <Button variant="ghost" className="rounded-full text-card-foreground">
            <UserIcon className="h-6 w-6" />
          </Button>
        </div>
      </header>
      <main className="p-4 md:p-10">
        <section className="mb-8">
          <h2 className="text-2xl font-bold text-card-foreground">Average Activity Strength:</h2>
          <div className="flex items-center mt-2">
            <Progress value={68} className="w-full h-4 bg-primary" />
            <span className="ml-2 text-lg font-bold text-card-foreground">68%</span>
          </div>
        </section>
        <section className="grid gap-4 md:grid-cols-3">
          <Card className="col-span-2">
            <CardHeader className="flex items-center justify-between">
              <div>
                <Avatar>
                  <AvatarImage src="/placeholder-user.jpg" />
                  <AvatarFallback>U</AvatarFallback>
                </Avatar>
                <h3 className="text-xl font-bold text-card-foreground">Usman</h3>
                <p className="text-sm text-muted-foreground">Intended field(s) of study: Psychology, Sociology</p>
                <p className="text-sm text-muted-foreground">Primary Interests: Environmental Club, Debate Team</p>
              </div>
            </CardHeader>
            <CardContent className="grid gap-4 md:grid-cols-2">
              <div className="p-4 bg-card rounded-lg shadow">
                <h4 className="text-lg font-bold text-card-foreground">Leadership Activities</h4>
                <p className="text-3xl font-bold text-card-foreground">7</p>
              </div>
              <div className="p-4 bg-card rounded-lg shadow">
                <h4 className="text-lg font-bold text-card-foreground">Community Service</h4>
                <p className="text-3xl font-bold text-card-foreground">3</p>
              </div>
              <div className="p-4 bg-card rounded-lg shadow">
                <h4 className="text-lg font-bold text-card-foreground">Category Breakdown</h4>
                <RadarchartChart className="w-full aspect-[4/3]" />
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle className="text-card-foreground">AI Suggestions</CardTitle>
              <Button variant="outline" className="ml-auto text-card-foreground">
                Regenerate
              </Button>
            </CardHeader>
            <CardContent>
              <p className="text-card-foreground">
                Based on your activity list, here is my evaluation and suggestions for improvement:
              </p>
              <ul className="list-disc list-inside text-card-foreground">
                <li>
                  Your activities show a strong focus on social justice, computer/technology, and internships, which is
                  great for showcasing your diverse skills and interests.
                </li>
                <li>However, it seems like you may have too many internship activities.</li>
              </ul>
            </CardContent>
          </Card>
        </section>
        <Tabs defaultValue="time-summary" className="mt-8">
          <TabsList>
            <TabsTrigger value="time-summary">Time Summary</TabsTrigger>
            <TabsTrigger value="activity-list">Activity List</TabsTrigger>
          </TabsList>
          <TabsContent value="time-summary">
            <Card>
              <CardHeader className="flex items-center justify-between">
                <CardTitle className="text-card-foreground">Average Time Summary</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="p-4 bg-card rounded-lg shadow">
                  <h4 className="text-lg font-bold text-card-foreground">Activity Time Summary</h4>
                  <BarchartChart className="w-full aspect-[4/3]" />
                </div>
              </CardContent>
            </Card>
          </TabsContent>
          <TabsContent value="activity-list">
            <Card>
              <CardHeader className="flex items-center justify-between">
                <CardTitle className="text-card-foreground">Activity List</CardTitle>
                <div className="flex items-center space-x-2">
                  <Button variant="outline" className="ml-auto text-card-foreground">
                    Upload Common App Activities PDF
                  </Button>
                  <Button variant="outline" className="ml-auto text-card-foreground">
                    Add Activity
                  </Button>
                </div>
              </CardHeader>
              <CardContent>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Activity</TableHead>
                      <TableHead>Hours</TableHead>
                      <TableHead>Category</TableHead>
                      <TableHead>Actions</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow>
                      <TableCell className="font-medium">Environmental Club</TableCell>
                      <TableCell>120</TableCell>
                      <TableCell>Community Service</TableCell>
                      <TableCell>
                        <Button variant="outline" size="icon" className="text-card-foreground">
                          <FilePenIcon className="h-4 w-4" />
                        </Button>
                        <Button variant="outline" size="icon" className="text-card-foreground">
                          <TrashIcon className="h-4 w-4" />
                        </Button>
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell className="font-medium">Debate Team</TableCell>
                      <TableCell>80</TableCell>
                      <TableCell>Leadership</TableCell>
                      <TableCell>
                        <Button variant="outline" size="icon" className="text-card-foreground">
                          <FilePenIcon className="h-4 w-4" />
                        </Button>
                        <Button variant="outline" size="icon" className="text-card-foreground">
                          <TrashIcon className="h-4 w-4" />
                        </Button>
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell className="font-medium">Internship at ABC Corp</TableCell>
                      <TableCell>160</TableCell>
                      <TableCell>Internship</TableCell>
                      <TableCell>
                        <Button variant="outline" size="icon" className="text-card-foreground">
                          <FilePenIcon className="h-4 w-4" />
                        </Button>
                        <Button variant="outline" size="icon" className="text-card-foreground">
                          <TrashIcon className="h-4 w-4" />
                        </Button>
                      </TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </main>
    </div>)
  );
}

function BellIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9" />
      <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0" />
    </svg>)
  );
}


function FilePenIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M12 22h6a2 2 0 0 0 2-2V7l-5-5H6a2 2 0 0 0-2 2v10" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
      <path d="M10.4 12.6a2 2 0 1 1 3 3L8 21l-4 1 1-4Z" />
    </svg>)
  );
}




function LogInIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4" />
      <polyline points="10 17 15 12 10 7" />
      <line x1="15" x2="3" y1="12" y2="12" />
    </svg>)
  );
}





function TrashIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>)
  );
}


function UserIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>)
  );
}


function XIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>)
  );
}

