/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/I2jERzmzx2K
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import { ChartTooltipContent, ChartTooltip, ChartContainer } from "@/components/ui/chart"
import { PolarAngleAxis, PolarGrid, Radar, RadarChart, CartesianGrid, XAxis, Line, LineChart } from "recharts"

export function home() {
  return (
    (<div
      className="flex flex-col w-full min-h-screen bg-background text-foreground">
      <header className="flex items-center justify-between h-16 px-4 bg-card border-b">
        <div className="flex items-center">
          <img src="/placeholder.svg" alt="Logo" className="h-10" />
          <span className="ml-2 text-lg font-semibold">gyde.ai</span>
          <span className="ml-2 text-sm text-muted-foreground">Open Beta</span>
        </div>
        <nav className="flex items-center space-x-4">
          <Link href="#" className="text-sm font-medium text-primary" prefetch={false}>
            Home
          </Link>
          <Link href="#" className="text-sm text-muted-foreground" prefetch={false}>
            Essays
          </Link>
          <Link href="#" className="text-sm text-muted-foreground" prefetch={false}>
            Colleges
          </Link>
          <Link href="#" className="text-sm text-muted-foreground" prefetch={false}>
            Activities
          </Link>
          <Link href="#" className="text-sm text-muted-foreground" prefetch={false}>
            Planner
          </Link>
        </nav>
        <div className="flex items-center space-x-4">
          <Button variant="ghost" size="icon">
            <BellIcon className="w-6 h-6 text-muted-foreground" />
          </Button>
          <Button variant="ghost" size="icon">
            <UserIcon className="w-6 h-6 text-muted-foreground" />
          </Button>
        </div>
      </header>
      <main className="flex flex-col flex-1 p-4 space-y-4 md:p-6 lg:p-8 bg-muted">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold">Welcome, USMAN OMER</h1>
          </div>
          <div className="flex items-center space-x-2">
            <span className="text-sm text-muted-foreground">Student Profile</span>
            <div className="relative w-64 h-4 bg-muted/50 rounded-full">
              <div
                className="absolute top-0 left-0 h-4 bg-primary rounded-full"
                style={{ width: "100%" }} />
            </div>
            <span className="text-sm text-muted-foreground">100%</span>
            <Button variant="outline" className="text-primary">
              View Profile
            </Button>
          </div>
        </div>
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
          <Card className="col-span-2 bg-card">
            <CardHeader>
              <CardTitle>Upcoming Deadlines</CardTitle>
            </CardHeader>
            <CardContent className="grid grid-cols-1 gap-4 md:grid-cols-2">
              <div className="p-4 border rounded-md bg-background">
                <img src="/placeholder.svg" alt="Yale University" className="w-10 h-10" />
                <h3 className="mt-2 text-lg font-semibold">Yale University</h3>
                <p className="text-sm text-muted-foreground">New Haven, Connecticut</p>
                <p className="text-sm">Nov 1, 2024</p>
                <p className="text-sm text-muted-foreground">Early Decision</p>
              </div>
              <div className="p-4 border rounded-md bg-background">
                <img src="/placeholder.svg" alt="Princeton University" className="w-10 h-10" />
                <h3 className="mt-2 text-lg font-semibold">Princeton University</h3>
                <p className="text-sm text-muted-foreground">Princeton, New Jersey</p>
                <p className="text-sm">Nov 1, 2024</p>
                <p className="text-sm text-muted-foreground">Early Decision</p>
              </div>
            </CardContent>
          </Card>
          <Card className="bg-card">
            <CardHeader>
              <CardTitle>Activities</CardTitle>
            </CardHeader>
            <CardContent>
              <RadarchartChart className="w-full h-64" />
            </CardContent>
          </Card>
        </div>
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
          <Card className="col-span-2 bg-card">
            <CardHeader className="flex justify-between">
              <CardTitle>Essay Editor</CardTitle>
              <Button variant="outline" className="text-primary">
                View Essays
              </Button>
            </CardHeader>
            <CardContent>
              <ul className="space-y-2">
                <li
                  className="flex items-center justify-between p-2 border rounded-md bg-background">
                  <div className="flex items-center space-x-2">
                    <img src="/placeholder.svg" alt="Princeton University" className="w-5 h-5" />
                    <span className="text-sm font-medium">Princeton University</span>
                  </div>
                  <span className="text-sm">Essay 4 Princeton University</span>
                </li>
                <li
                  className="flex items-center justify-between p-2 border rounded-md bg-background">
                  <div className="flex items-center space-x-2">
                    <img src="/placeholder.svg" alt="Free Write" className="w-5 h-5" />
                    <span className="text-sm font-medium">Free Write</span>
                  </div>
                  <span className="text-sm">New Essay1</span>
                </li>
                <li
                  className="flex items-center justify-between p-2 border rounded-md bg-background">
                  <div className="flex items-center space-x-2">
                    <img src="/placeholder.svg" alt="Free Write" className="w-5 h-5" />
                    <span className="text-sm font-medium">Free Write</span>
                  </div>
                  <span className="text-sm">New Essay1</span>
                </li>
              </ul>
            </CardContent>
          </Card>
          <Card className="bg-card">
            <CardHeader>
              <CardTitle>Planner</CardTitle>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Date</TableHead>
                    <TableHead>Event</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow>
                    <TableCell>27 July, Saturday</TableCell>
                    <TableCell>Princeton University Essay 1 Draft 1</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>7 August, Wednesday</TableCell>
                    <TableCell>Princeton University Essay 2 Draft 1</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>18 August, Sunday</TableCell>
                    <TableCell>Princeton University Essay 6 Draft 1</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>29 August, Thursday</TableCell>
                    <TableCell>Princeton University Essay 7 Draft 1</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>6 September, Friday</TableCell>
                    <TableCell>Princeton University Essay 1 Draft 2</TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </div>
      </main>
    </div>)
  );
}

function BellIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9" />
      <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0" />
    </svg>)
  );
}


function LinechartChart(props) {
  return (
    (<div {...props}>
      <ChartContainer
        config={{
          desktop: {
            label: "Desktop",
            color: "hsl(var(--chart-1))",
          },
        }}>
        <LineChart
          accessibilityLayer
          data={[
            { month: "January", desktop: 186 },
            { month: "February", desktop: 305 },
            { month: "March", desktop: 237 },
            { month: "April", desktop: 73 },
            { month: "May", desktop: 209 },
            { month: "June", desktop: 214 },
          ]}
          margin={{
            left: 12,
            right: 12,
          }}>
          <CartesianGrid vertical={false} />
          <XAxis
            dataKey="month"
            tickLine={false}
            axisLine={false}
            tickMargin={8}
            tickFormatter={(value) => value.slice(0, 3)} />
          <ChartTooltip cursor={false} content={<ChartTooltipContent hideLabel />} />
          <Line
            dataKey="desktop"
            type="natural"
            stroke="var(--color-desktop)"
            strokeWidth={2}
            dot={false} />
        </LineChart>
      </ChartContainer>
    </div>)
  );
}


function RadarchartChart(props) {
  return (
    (<div {...props}>
      <ChartContainer
        config={{
          desktop: {
            label: "Desktop",
            color: "hsl(var(--chart-1))",
          },
        }}
        className="mx-auto aspect-square max-h-[250px]">
        <RadarChart
          data={[
            { month: "January", desktop: 186 },
            { month: "February", desktop: 305 },
            { month: "March", desktop: 237 },
            { month: "April", desktop: 273 },
            { month: "May", desktop: 209 },
            { month: "June", desktop: 214 },
          ]}>
          <ChartTooltip cursor={false} content={<ChartTooltipContent />} />
          <PolarAngleAxis dataKey="month" />
          <PolarGrid />
          <Radar dataKey="desktop" fill="var(--color-desktop)" fillOpacity={0.6} />
        </RadarChart>
      </ChartContainer>
    </div>)
  );
}


function UserIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>)
  );
}


function XIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>)
  );
}
